OPT_DEFS += -DHOST_VUSB

SRC =	usbdrv.c \
	usbdrvasm.S \
	oddebug.c \
	sendchar_uart.c \
	uart.c

SRC +=	$(TARGET_SRC)


# C source file search path
VPATH = $(TARGET_DIR):$(COMMON_DIR):$(COMMON_DIR)/vusb:$(COMMON_DIR)/vusb/usbdrv
